repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0  # Specify the version of Black
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0  # Specify the version of Flake8
    hooks:
      - id: flake8

